language: node_js
node_js:
    - '0.10.21'

sudo: false

script:
    - "npm run test-cov"

services:
    - mongodb

after_script: "npm install coveralls && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage"